# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: false
sudo: false
cache: packages

r:
- 3.3
- oldrel
- release
- devel

after_success:
  - Rscript -e 'covr::codecov()'

r_github_packages:
  - tidyverse/tidytemplate
